-- MySQL Script generated by MySQL Workbench
-- 02/05/15 21:54:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema calpolyiot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema calpolyiot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `calpolyiot` ;
USE `calpolyiot` ;

-- -----------------------------------------------------
-- Table `calpolyiot`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calpolyiot`.`user` ;

CREATE TABLE IF NOT EXISTS `calpolyiot`.`user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(15) NOT NULL DEFAULT '',
  `email` varchar(45) DEFAULT NULL,
  `password` varchar(15) NOT NULL,
  `lastName` varchar(30) DEFAULT NULL,
  `firstName` varchar(30) DEFAULT NULL,
  `dateAdded` date DEFAULT NULL,
  PRIMARY KEY (`id`,`username`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `username_UNIQUE` (`username`),
  UNIQUE KEY `email_UNIQUE` (`email`));


-- -----------------------------------------------------
-- Table `calpolyiot`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calpolyiot`.`device` ;

CREATE TABLE IF NOT EXISTS `calpolyiot`.`device` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `deviceName` varchar(30) DEFAULT NULL,
  `endpoint` varchar(100) DEFAULT NULL,
  `dateAdded` date DEFAULT NULL,
  `access` varchar(15) DEFAULT 'private',
  `ownerId` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `device_fk1_idx` (`ownerId`),
  CONSTRAINT `device_fk1` FOREIGN KEY (`ownerId`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `calpolyiot`.`sensorlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calpolyiot`.`sensorlist` ;

CREATE TABLE IF NOT EXISTS `calpolyiot`.`sensorlist` (
  `endpoint` varchar(100) DEFAULT NULL,
  `sensor` varchar(45) DEFAULT NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
